### PR TITLE
Fix Symfony 5.2 compatibility because Kernel::preBoot() broke the current implementation

### PR DESCRIPTION
**Pull request by t-richard**

### CODE REVIEW

**Comment by t-richard** [comment]
Following investigation on why the tests are NOT failing here.

We are actually testing with the console which also uses the Kernel but the console is not calling preBoot (this function was introduced for some http related feature) so it doesn't fail and work as expected but in a console context.

We should probably change the tests to simulate an HttpRequest instead

**Comment by t-richard** [comment]
Ok, I fixed the tests to fail on Symfony 5.2 where the behaviour of `Kernel::handle()` changed. I've also added PHP 8.0 to the version matrix because support was added in #34 but the CI, tests and dev-dependencies weren't updated. 

[This commit](https://github.com/brefphp/symfony-bridge/pull/37/commits/07f8e868012715ff81a749bd749ab19103a2bf85) is a point at which the tests are failing but the bug was not resolved and we can see all 5.2 tests on all PHP versions are failing while others are fine.

image

I'll now work on making it all green again :traffic_light:

**Review by mnapoli — APPROVED** [review]
Thank you for going through all of that!

**Comment by t-richard** [comment]
@mnapoli you're welcome :slightly_smiling_face: 

That was easier than I thought once I understood why the tests were not failing on 5.2

**Pull request merged**
