### PR TITLE
Test different Symfony versions

### PR DESCRIPTION
**Pull request by Nyholm**
I also fixed a small bug (same as #23)

### CODE REVIEW

**Comment by Nyholm** [comment]
PR is rebased and build is green.

The functional tests will now respect the `SYMFONY_REQUIRE` env variable

**Comment by Nyholm** [comment]
Thank you for the review

**Comment by mnapoli** [comment]
Guys, in case of conflicts (with #27) could we please wait a little bit before merging?

**Comment by Nyholm** [comment]
Oops, Sorry if I was too quick

**Comment by mnapoli** [comment]
It's OK I'll try to find some time tonight to continue my PR.

**Pull request merged**
