### PR TITLE
Cleaned up some files

### PR DESCRIPTION
**Pull request by Nyholm**
This basically remove comments and files not needed.

### CODE REVIEW

**Comment by mnapoli** [comment]
Is there a reason to diverge from the standard Symfony project?

I am afraid upgrading will be made harder, as well as following any tutorial/documentation on installing extra packages, or debugging (e.g. I debug some stuff in dev mode).

I agree that a lot of this is noise, but any change we introduce here is something we have to be aware of, and that we have to maintain down the road.

**Comment by Nyholm** [comment]
I just merged files and removed comments. I also removed config for non-prod environment. 

This config will be okey for latest version of Symfony 2 more years (probably more but it is impossible to know) and with #24 we test different Symfony versions. 

I dont see any risk with this change.

**Comment by mnapoli** [comment]
> This config will be okey for latest version of Symfony 2 more years

Respectfully, you know that. I don't, most other people will not be 100% sure as well.

Modified code is code we have to maintain, and I want to maintain as little as possible 😄  Here this is making my job, and the job of other possible contributors and maintainers, harder and I don't see any benefit.

**Comment by Nyholm** [comment]
> Modified code is code we have to maintain, and I want to maintain as little as possible

Yeah, That is why I removed 6 config files and 40 lines of noice. I want to have less code, less config, less files.

**Comment by mnapoli** [comment]
Sorry, I'll try to reformulate. I understand and I agree that it is less code.

But at the moment, that code is generated by Symfony.

For example, let's say we want to upgrade to a new Symfony version, we can:

- upgrade Symfony via Composer and re-sync all recipes
- or event delete/recreate that Symfony app from scratch

In both cases, we can review the diff and:

- if it's a Bref-related change -> keep it
- if it's not -> we don't care since it's Symfony updating itself, we can safely apply the new code

Does that make sense?

If we change the code, it becomes our code because it is no longer generated.

**Comment by Nyholm** [comment]
> Does that make sense?

I understand your point. But I don't think it makes sense. =)

-------

> But at the moment, that code is generated by Symfony.

No. That code is generated by recipes. Yes, the recipes lives in the Symfony organisation, but just because a recipe change, you dont need to change your config. 

----------

If you want to update Symfony. You run modify the versions in `composer.json` and run `composer update`. You can update to any 5.x version until November 2024 without any issues. Most likely you may continue on the 6.x version for even longer. 

I dont see any reasons to keep around "example files" or "easy to get started to build your app"-files for this long just to make a potential future diff easier to read.

**Comment by mnapoli** [comment]
> No. That code is generated by recipes. Yes, the recipes lives in the Symfony organisation, but just because a recipe change, you dont need to change your config.

That's true. However, these are still generated files. I said "by Symfony" but actually we don't really care by who, the point is that they are generated.

> If you want to update Symfony. You run modify the versions in composer.json and run composer update. You can update to any 5.x version until November 2024 without any issues. Most likely you may continue on the 6.x version for even longer.

I had too many troubles with updating Symfony (the last one was just this week, upgrading from 4.3 to 5.0 and I had sooo many issues because of recipes and flex). I really want to stay away as much as possible from this.

> I dont see any reasons to keep around "example files" or "easy to get started to build your app"-files for this long just to make a potential future diff easier to read.

You just said it: "just to make a potential future diff easier to read." Let's take your question the other way around:

Why should we change the generated code? What do we gain by merging this PR?

Less code, sure, but this is code we don't look at. So why?

If it's a matter of cleanliness, then "diff easier to read" > "cleanliness of invisible artifact code" to me.

**Comment by mnapoli** [comment]
Upgrading Symfony is incredibly hard, I'll refrain from doing anything custom in the test app.

**Pull request closed without merging**
