### PR TITLE
Allow Bref v2

### PR DESCRIPTION
**Pull request by mnapoli**

### CODE REVIEW

**Comment by mnapoli** [comment]
I don't understand Symfony anymore 🤦

**Comment by t-richard** [comment]
That's a composer issue, not (really) a Symony issue.

Since 2.2, composer requires you to allow plugins explicitly and I guess in the tests fixtures, it's not the case

**Comment by t-richard** [comment]
I merged #64, this should fix the CI here

**Comment by mnapoli** [comment]
Thanks! I'm rebasing and giving this a try!

**Pull request merged**
